### ISSUE TITLE
Provide API so clients can get templates

### ISSUE THREAD

**Issue by spdegabrielle** [nixin72/from-template#15]
currently sauron-ide has templates hard coded: 

https://github.com/racket-tw/sauron/blob/1000f38f257e1792bdaf38b7470e73eca480d316/project/manager.rkt#L87

it would be better if there was a call they could make.

e.g.
```
(require from-template)
(define templates (get-templates))
...
```

**Comment by spdegabrielle** [comment]
the `list-templates` function to return a list of hashes of all the templates available.

**Comment by spdegabrielle** [comment]
#18 provides `list-templates` function

@spdegabrielle to make PR for Sauron https://github.com/racket-tw/sauron

e.g.
```
(require from-template)
(define templates (templatehash->list (list-templates)))
...
```

https://github.com/racket-tw/sauron/blob/1000f38f257e1792bdaf38b7470e73eca480d316/project/manager.rkt#L87

**Comment by nixin72** [comment]
Can this also get closed now too @spdegabrielle?

**Comment by spdegabrielle** [comment]
Closed with my thanks!
👏👏👏
