### ISSUE TITLE
raco new --list fails silently

### ISSUE THREAD

**Issue by spdegabrielle** [nixin72/from-template#19]
`raco new --list` fails silently

```
% raco new                      
% ls
% raco new -list
% raco new      
% raco new -h
qi % 
```

**Comment by nixin72** [comment]
Thanks for making an issue for this, I've fixed it - I was unaware that I needed to tell the info.rkt to use a specific module for it to run the `main`.

**Comment by spdegabrielle** [comment]
Thank you. I was madly scrabbling through main.rkt thinking this all looks fine!
