### ISSUE TITLE
raco new has no result?

### ISSUE THREAD

**Issue by dannypsnl** [nixin72/from-template#23]
I run

```shell
raco new gui-app hello
```

and cannot see `hello/` be created.

Racket version: Racket v8.3 [cs].
OS: macOS 12.1
Arch: arm64

The source is when I test this https://github.com/racket-tw/sauron/commit/0736101511800b29309a2fe05557003ef98574bb, and then check in the command line, it's still happened

**Comment by dannypsnl** [comment]
It got fix after update to fb3c5520a491e55c7.

**Comment by spdegabrielle** [comment]
That is a relief.
Thank you for your vigilance. It is appreciated.
Best wishes,
Stephen

**Comment by dannypsnl** [comment]
sorry I didn't collect the correct version info QQ, I think it still would be good to know which version is broken
