### ISSUE TITLE
raco new list errors with 404

### ISSUE THREAD

**Issue by halhenke** [nixin72/from-template#26]
```
raco new list
#(struct:exn:fail:contract apply: contract violation
  expected: list?
  given: '404: #<continuation-mark-set>)


Hmm, an unexpected error has occured...
If you'd like, we'd really appreciate it if you filed a bug report at
https://github.com/nixin72/from-template/issues/new
```

**Comment by nixin72** [comment]
Hey @halhenke, thanks for opening the issue. This project has moved however to https://github.com/racket-templates/new. If you download the new version of the tool the issue may have been fixed already. If not, if you could raise the issue over there it would be appreciated.
